name: pystac-env
channels:
  - defaults
dependencies:
  - python=3.8
  - ipython
  - matplotlib
  - ca-certificates
  - certifi
  - openssl
  - requests
  - rasterio
  - numpy
  - pandas
  - ipykernel
  - xcube
  - pip
  - pip:
    - pystac
    - pystac-client
    - pyproj
